import { NextRequest, NextResponse } from 'next/server';
import { randomBytes } from 'node:crypto';
import { z } from 'zod';
import { prisma, DEMO_MODE } from '@/lib/db';
import { requireRole } from '@/lib/auth';
import { rateLimit, ipOf } from '@/lib/rate-limit';
import { recordActivity } from '@/lib/notify';
import { fail } from '@/lib/ops-api';
import { ghs } from '@/lib/money';

const Schema = z.object({ amount: z.number().min(1).max(200000), description: z.string().max(200).optional() });

/** POST /api/technician/bookings/[id]/pay — collect payment: mints a BOOKING payment link (QR + WhatsApp) */
export async function POST(req: NextRequest, ctx: { params: Promise<{ id: string }> }) {
  const s = await requireRole('TECHNICIAN', 'ADMIN', 'SUPER_ADMIN').catch(() => null);
  if (!s) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  const rl = rateLimit(`techpay:${s.userId}`, 10, 60_000);
  if (!rl.ok) return fail('Too many requests.', 429);
  const { id } = await ctx.params;
  const parsed = Schema.safeParse(await req.json().catch(() => null));
  if (!parsed.success) return fail('Amount must be at least ₵1.');

  const b = await prisma.booking.findUnique({ where: { id } });
  if (!b) return fail('Booking not found.', 404);
  const tech = await prisma.technician.findUnique({ where: { userId: s.userId } });
  const isAdmin = s.role === 'ADMIN' || s.role === 'SUPER_ADMIN';
  if (!isAdmin && (!tech || b.technicianId !== tech.id)) return fail('This job is not assigned to you.', 403);

  const link = await prisma.paymentLink.create({
    data: {
      code: randomBytes(4).toString('hex').toUpperCase(),
      label: `Job ${b.bookingNo}`,
      description: parsed.data.description ?? `On-site payment for ${b.bookingNo} — GabiElectricals`,
      amount: parsed.data.amount, forType: 'BOOKING', forId: b.id, createdBy: s.userId,
      expiresAt: new Date(Date.now() + 24 * 3600_000), qrSeed: randomBytes(8).toString('hex'),
    },
  });
  await prisma.bookingEvent.create({ data: { bookingId: b.id, status: b.status, note: `Payment link ${link.code} for ${ghs(parsed.data.amount)} generated by tech` } });
  await recordActivity(s.userId, 'TECH_PAY_LINK', 'PaymentLink', link.id);
  const url = `${process.env.NEXT_PUBLIC_SITE_URL ?? (DEMO_MODE ? 'http://localhost:3000' : '')}/pay/${link.code}`;
  return NextResponse.json({ ok: true, code: link.code, url });
}
