import type { Metadata } from 'next';
import { LegalShell, H2 } from '@/components/LegalShell';

export const metadata: Metadata = { title: 'Terms & Conditions', description: 'GabiElectricals terms of sale, delivery, booking and payment — Ghana.' };

export default function TermsPage() {
  return (
    <LegalShell title="Terms & Conditions" updated="30 September 2026">
      <p>These terms govern purchases from gabielectricals.com and services booked through our platform. By ordering or booking you agree to them.</p>
      <H2>1. Products & pricing</H2>
      <p>All products are sold as genuinely manufactured goods sourced from authorised channels. Prices are in Ghana Cedis (GHS) and include VAT at the prevailing rate (currently 15%) unless stated otherwise; applicable levies are shown at checkout. We reserve the right to correct pricing errors; if a corrected price is higher we will contact you before charging.</p>
      <H2>2. Orders & delivery</H2>
      <p>An order is confirmed when payment (or deposit) is received or, for pay-on-delivery, when dispatch occurs. Delivery windows are estimates. Risk in goods passes on delivery to you or your nominated recipient. Orders unclaimed for 7 days after arrival may be returned and refunded less delivery cost.</p>
      <H2>3. Services & bookings</H2>
      <p>Bookings hold a time slot; deposits are per the quoted policy. Reschedules are permitted up to 3 times with at least 24 hours’ notice. Emergency call-out surcharges apply outside standard hours as shown at booking. Quote prices are valid until their stated expiry. Site conditions materially different from the description may change the final price — we will always seek your approval first.</p>
      <H2>4. Payment</H2>
      <p>We accept MTN MoMo, Telecel Cash, AT Money, Visa/Mastercard (hosted, PCI-compliant processor), bank transfer/GhIPSS, QR payment, and pay-on-delivery where enabled. We never store card data. Payment links expire; expired links can be regenerated by staff.</p>
      <H2>5. Warranty & returns</H2>
      <p>See our <a href="/returns" className="text-blue font-semibold">Refund & Warranty Policy</a>. Manufacturer warranties do not limit your statutory rights.</p>
      <H2>6. Liability</H2>
      <p>To the extent permitted by Ghanaian law, our liability for any claim is limited to the amount paid for the affected product or service. We are not liable for indirect losses, but nothing here excludes liability for personal injury caused by our negligence or for fraudulent misrepresentation of product genuineness.</p>
      <H2>7. Referrals & affiliate</H2>
      <p>Referral rewards require a genuine first purchase of the minimum order value. Self-referral, duplicate accounts or incentivised sign-ups void rewards and may close the account. Affiliate commissions are payable 14 days after the delivered order window.</p>
      <H2>8. Disputes</H2>
      <p>We attempt resolution in good faith within 14 days, then via the Ghanaian courts of competent jurisdiction. Nothing prevents you from complaining to the Data Protection Commission or the relevant consumer authority.</p>
    </LegalShell>
  );
}
