// Generates src/components/icon-paths.ts from downloaded Material Symbols SVGs.
// Run: node scripts/gen-icons.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, basename } from 'node:path';

const dir = new URL('../src/components/icons/', import.meta.url).pathname;
const out = new URL('../src/components/icon-paths.ts', import.meta.url).pathname;

const entries = [];
for (const f of readdirSync(dir).sort()) {
  if (!f.endsWith('.svg')) continue;
  const name = basename(f, '.svg');
  const svg = readFileSync(join(dir, f), 'utf8');
  const paths = [...svg.matchAll(/<path\s+d="([^"]+)"/g)].map(m => m[1]);
  if (!paths.length) { console.warn('no paths in', f); continue; }
  entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(paths)},`);
}

const ts = `// AUTO-GENERATED by scripts/gen-icons.mjs — official Google Material Symbols (Rounded).
// Do not edit by hand.
export const ICON_PATHS = {
${entries.join('\n')}
} as const;
export type IconName = keyof typeof ICON_PATHS;
`;
writeFileSync(out, ts);
console.log(`wrote ${out} with ${entries.length} icons`);
