// GabiElectricals seed catalog — Ghana market, premium positioning.
// Compact tuples: n=name, c=category slug, b=brand slug, p=sell GHS, cost=cost GHS,
// cmp=compare-at GHS, s=stock, w=warranty months, d=description, sp=[specs], tg=[tags]

export const CATEGORIES = [
  { slug: 'cables-wires', name: 'Cables & Wires', icon: 'cable', order: 1, desc: 'Folded Cable, Eastern Electric and other certified pure-copper wires for every circuit in your home or site.' },
  { slug: 'switches-sockets', name: 'Switches & Sockets', icon: 'socket', order: 2, desc: 'MK, Legrand and Genesis faceplates and sockets that finish a room properly.' },
  { slug: 'breakers-boards', name: 'Breakers & Distribution Boards', icon: 'breaker', order: 3, desc: 'Schneider, ABB and Hager protection devices and consumer units installed to IEC standard.' },
  { slug: 'led-lighting', name: 'LED Lighting', icon: 'bulb', order: 4, desc: 'Panels, floodlights, downlights and solar street lights that cut your ECG bill.' },
  { slug: 'solar-inverters', name: 'Solar Panels & Inverters', icon: 'solar', order: 5, desc: 'Panels, hybrid inverters and mounting kits for dependable power in dumsor season.' },
  { slug: 'batteries-ups', name: 'Batteries & UPS / Stabilizers', icon: 'battery', order: 6, desc: 'Tubular and gel storage banks, UPS units and AVRs sized for Ghana loads.' },
  { slug: 'generators', name: 'Generators', icon: 'gen', order: 7, desc: 'Petrol, diesel and inverter generators — from light home sets to soundproof estate units.' },
  { slug: 'tools-testers', name: 'Tools & Testers', icon: 'tool', order: 8, desc: 'Fluke and Bosch test gear and pro hand tools trusted by certified electricians.' },
  { slug: 'fans-ac', name: 'Fans & AC Accessories', icon: 'fan', order: 9, desc: 'Ceiling and exhaust fans plus AC PCBs, remotes, brackets and copper piping.' },
  { slug: 'extensions-surge', name: 'Extension Cords & Surge Protectors', icon: 'plug', order: 10, desc: 'Heavy-duty extension reels and surge blocks that actually protect your TV and fridge.' },
  { slug: 'security-cctv', name: 'Security — CCTV, Alarms & Smart Locks', icon: 'cam', order: 11, desc: 'Hikvision and Ezviz camera kits, alarm systems and smart locks with installation support.' },
  { slug: 'smart-home', name: 'Smart Home Devices', icon: 'wifi', order: 12, desc: 'WiFi switches, smart bulbs, sensors and energy monitors controlled from your phone.' },
  { slug: 'prepaid-meters', name: 'Prepaid Meter Accessories', icon: 'meter', order: 13, desc: 'Keypads, meter boxes, card readers and CT sensors for ECG prepaid setups.' },
];

export const BRANDS = [
  'Folded Cable', 'Eastern Electric', 'Nexans', 'MK Electric', 'Schneider', 'ABB', 'Legrand',
  'Genesis', 'BVW', 'Philips', 'Müller Light', 'Luminous', 'Growatt', 'Elepaq', 'FSP',
  'Hercules', 'Yamaha', 'Mikano', 'Fluke', 'Bosch', 'Megger', 'Sunon', 'Hikvision', 'Ezviz',
  'Sonoff', 'Moko', 'Aptek', 'Tiger Soft', 'Carlit', 'Zinsaco',
];

type P = {
  n: string; c: string; b: string; p: number; cost: number; cmp?: number; s: number; w: number;
  d: string; sp: [string, string][]; tg?: string[]; badge?: string[]; feat?: boolean; best?: boolean; new?: boolean;
};

const genuine = ['100% Genuine'];
const warranty = ['100% Genuine', 'Warranty Included'];
const sameDay = ['100% Genuine', 'Same-Day Delivery in Accra'];

export const PRODUCTS: P[] = [
  // ── Cables & Wires (7)
  { n: 'Folded Cable 1.5mm² Single Core — 100m Roll', c: 'cables-wires', b: 'Folded Cable', p: 385, cost: 295, cmp: 450, s: 42, w: 12, d: 'The roll Ghana builders trust. Pure annealed copper to GSEC standard, ideal for lighting circuits and ring finals in homes and offices.', sp: [['Conductor', '99.97% pure annealed copper'], ['Insulation', 'PVC 450/750V'], ['Length', '100m roll'], ['Certification', 'GSEC & IEC 60227']], tg: ['bestseller'], best: true, badge: sameDay },
  { n: 'Folded Cable 2.5mm² Single Core — 100m Roll', c: 'cables-wires', b: 'Folded Cable', p: 565, cost: 435, cmp: 650, s: 38, w: 12, d: 'Workhorse of the Ghanaian home wiring market. Sized for radial socket circuits, kitchen spurs and AC feeders with genuine copper throughout.', sp: [['Conductor', 'Pure copper, class 2'], ['Rating', '450/750V'], ['Length', '100m'], ['Use', 'Socket radials, AC spurs']], tg: ['bestseller'], feat: true, best: true, badge: sameDay },
  { n: 'Eastern Electric 4mm² Single Core — 100m Roll', c: 'cables-wires', b: 'Eastern Electric', p: 890, cost: 690, s: 24, w: 12, d: 'Eastern Copperbelt grade 4mm² for high-current radial circuits, cooker feeds and small power distribution. Every roll serial-tracked for genuineness.', sp: [['Conductor', 'Pure copper'], ['Size', '4mm²'], ['Voltage', '450/750V'], ['Length', '100m']], badge: warranty },
  { n: 'Nexans 6mm² Single Core — 100m Roll', c: 'cables-wires', b: 'Nexans', p: 1280, cost: 990, s: 15, w: 24, d: 'European-spec Nexans 6mm² for tails, shower units and long heavy loads where volt-drop matters. Imported stock, never reeled down.', sp: [['Standard', 'EN/IEC harmonised'], ['Size', '6mm²'], ['Insulation', 'LSZH available on request']], badge: warranty },
  { n: 'Folded Cable 2.5mm² Flat Twin & Earth — 50m', c: 'cables-wires', b: 'Folded Cable', p: 480, cost: 360, cmp: 540, s: 30, w: 12, d: 'Twin and earth for classic Ghanaian radial wiring — one roll carries live, neutral and CPC. Perfect for extensions and rewires.', sp: [['Cores', '2 × 2.5mm² + 1.5mm² CPC'], ['Length', '50m'], ['Type', 'Flat PVC sheathed']], badge: genuine },
  { n: 'BVW 3-Core Armoured 3×2.5mm² — per metre', c: 'cables-wires', b: 'BVW', p: 32, cost: 22, s: 800, w: 12, d: 'Steel-wire armoured submain cable for buried runs between meter and distribution board. Buy by the metre, cut on site.', sp: [['Type', 'SWA armoured'], ['Cores', '3 × 2.5mm²'], ['Use', 'Underground submains']], badge: genuine },
  { n: 'Cat6 UTP Ethernet Cable — 305m Box', c: 'cables-wires', b: 'Nexans', p: 1450, cost: 1120, s: 12, w: 6, d: 'Solid copper Cat6 for structured networking in offices and smart homes. Pure copper — no CCA junk.', sp: [['Category', 'Cat6 550MHz'], ['Length', '305m box'], ['Conductor', '23AWG solid copper']], tg: ['new'], new: true, badge: warranty },

  // ── Switches & Sockets (6)
  { n: 'MK Logic Metal 13A Switched Socket — White', c: 'switches-sockets', b: 'MK Electric', p: 92, cost: 62, cmp: 110, s: 120, w: 12, d: 'The socket Ghana electricians specify. Full brass internals, shuttered outlets and a snap action you can feel through the fingertips.', sp: [['Rating', '13A BS1363'], ['Finish', 'White / metal rocker'], ['Extras', 'Child protection shutters']], best: true, badge: genuine },
  { n: 'MK Logic Dual Switched Socket — White', c: 'switches-sockets', b: 'MK Electric', p: 128, cost: 88, s: 96, w: 12, d: 'Double 13A socket with two separate rockers — the standard for Ghanaian living rooms where one spur serves TV and decoder.', sp: [['Rating', '2 × 13A'], ['Plate', '86 × 86mm']], badge: genuine },
  { n: 'Legrand(Grid) 16A Double Socket — Grey', c: 'switches-sockets', b: 'Legrand', p: 105, cost: 72, cmp: 130, s: 84, w: 12, d: 'Legrand Grid faceplates with a slim, modern profile — a visible upgrade for new builds in East Legon and Takoradi.', sp: [['Rating', '16A'], ['Plate', 'Square grid module']], badge: genuine },
  { n: 'Genesis 15A Single Switch — 2-Gang Plate', c: 'switches-sockets', b: 'Genesis', p: 38, cost: 24, s: 200, w: 12, d: 'Locally loved Genesis switching at a fair premium price — high-impact nylon body rated for thousands of cycles.', sp: [['Rating', '15A 250V'], ['Cycles', '40,000 tested']], badge: genuine },
  { n: 'IP44 Weatherproof Switch & Socket Combo', c: 'switches-sockets', b: 'MK Electric', p: 148, cost: 102, s: 46, w: 12, d: 'Sealed combo for outdoor lighting, compound gates and service yards — survives the harmattan dust and rainy season downpours.', sp: [['Protection', 'IP44'], ['Contents', '1-gang switch + 13A socket']], badge: warranty },
  { n: 'BVW 32A Double Pole Isolator — Switch Disconnector', c: 'switches-sockets', b: 'BVW', p: 118, cost: 78, s: 60, w: 12, d: 'Locked-load isolator for AC units, water heaters and inverter feeds. Clear ON/OFF indication for safe isolation.', sp: [['Rating', '32A DP'], ['Use', 'AC & heater isolation']], badge: genuine },

  // ── Breakers & Distribution Boards (6)
  { n: 'Schneider Acti9 32A DP MCB — C Curve', c: 'breakers-boards', b: 'Schneider', p: 168, cost: 118, s: 90, w: 24, d: 'Acti9 protection for ring finals and radial socket circuits. True tripping curves — unlike the counterfeits flooding Makola.', sp: [['Rating', '32A, 6kA'], ['Curve', 'C'], ['Standard', 'EN 60898']], feat: true, badge: warranty },
  { n: 'ABB 63A 30mA RCBO — Type AC', c: 'breakers-boards', b: 'ABB', p: 415, cost: 305, cmp: 480, s: 40, w: 24, d: 'Combined overload + earth-fault protection. The single best upgrade for a Ghanaian home: protects people, not just cables.', sp: [['Rating', '63A / 30mA'], ['Type', 'RCBO'], ['Trip', '<40ms at 30mA']], badge: warranty },
  { n: 'Schneider 8-Way TP&N Consumer Unit — Surface', c: 'breakers-boards', b: 'Schneider', p: 520, cost: 380, s: 28, w: 24, d: 'Distribution board with copper busbar, neutral/earth rails and a clear front — the heart of a professional rewire.', sp: [['Ways', '8 TP&N'], ['IP', 'IP40'], ['Busbar', 'Copper']], badge: warranty },
  { n: 'Hager 4-Way Mini Distribution Board', c: 'breakers-boards', b: 'ABB', p: 265, cost: 185, s: 55, w: 24, d: 'Compact board for flats, shops and AC sub-circuits. DIN rail with blanking plates included.', sp: [['Ways', '4'], ['Format', 'Surface or flush']], badge: genuine },
  { n: 'SPN 2-Way IP65 Outdoor Board with Isolator', c: 'breakers-boards', b: 'BVW', p: 340, cost: 240, s: 34, w: 12, d: 'Weatherproof meter-tail board for compound and gate supplies, built to take the Ghana rain season.', sp: [['IP', 'IP65'], ['Ways', '2 SP + isolator']], badge: genuine },
  { n: 'Schneider 250A MCCB with Rotary Handle', c: 'breakers-boards', b: 'Schneider', p: 1850, cost: 1390, s: 10, w: 24, d: 'Moulded case breaker for commercial service entrances and estate submains — adjustable magnetic trip, true Schneider lineage.', sp: [['Rating', '250A'], ['Breaking', '25kA Icu'], ['Standard', 'IEC 60947-2']], badge: warranty },

  // ── LED Lighting (6)
  { n: 'Philips Master LED Bulb 9W — Pack of 4', c: 'led-lighting', b: 'Philips', p: 180, cost: 122, cmp: 220, s: 140, w: 24, d: 'E27 warm-white bulbs rated 15,000 hours — they survive Ghana voltage swings that kill cheap bulbs.', sp: [['Wattage', '9W = 60W incand.'], ['Lumens', '806lm'], ['Base', 'E27']], best: true, badge: warranty },
  { n: 'Müller Light Panel 36W 600×600 — Cool Daylight', c: 'led-lighting', b: 'Müller Light', p: 275, cost: 195, s: 88, w: 12, d: 'Ultra-slim LED panel for dropped ceilings in offices, clinics and shops. Glare-free flicker tested for Ghanaian mains.', sp: [['Wattage', '36W'], ['Size', '595×595mm'], ['CRI', '≥80']], feat: true, badge: genuine },
  { n: 'Floodlight LED 100W IP66 with Sensor', c: 'led-lighting', b: 'Sunon', p: 430, cost: 305, cmp: 520, s: 62, w: 12, d: 'Compound and forecourt lighting with PIR motion — security that switches on when trotro passes, off when it does not.', sp: [['Wattage', '100W'], ['IP', 'IP66'], ['Sensor', 'PIR 12m']], badge: genuine },
  { n: 'Solar Street Light 60W All-in-One — 3.2V LiFePO4', c: 'led-lighting', b: 'Müller Light', p: 985, cost: 690, s: 38, w: 24, d: 'Independent street lighting for estates and car parks — daylight charging, remote dimming, 3-night battery autonomy.', sp: [['Panel', 'Mono PERC'], ['Battery', 'LiFePO4 30Ah'], ['Modes', 'Remote 3-level dim']], tg: ['new'], new: true, badge: warranty },
  { n: 'LED Strip 5m 2835 Warm White + Remote', c: 'led-lighting', b: 'Carlit', p: 165, cost: 105, s: 110, w: 12, d: 'Cove and cabinet lighting with RF remote — the finish detail high-end Accra interiors ask for.', sp: [['Length', '5m reel'], ['LEDs', '2835, 60/m'], ['Control', 'RF remote dim']], badge: genuine },
  { n: 'Emergency LED Bulb 12W — 3hr Runtime', c: 'led-lighting', b: 'Zinsaco', p: 95, cost: 60, s: 150, w: 12, d: 'Keeps burning when ECG takes the light — built-in battery rated 3 hours after full charge. Dumsor essential.', sp: [['Runtime', '≥3 hours'], ['Wattage', '12W'], ['Base', 'B22']], best: true, badge: genuine },

  // ── Solar Panels & Inverters (6)
  { n: 'Mono PERC Solar Panel 250W', c: 'solar-inverters', b: 'Luminous', p: 1480, cost: 1120, cmp: 1750, s: 26, w: 120, d: 'Tier-A mono module with 25-year output warranty — engineered for Harmattan dust and coastal salt air.', sp: [['Peak', '250Wp'], ['Cell', 'Mono PERC'], ['Warranty', '25 yr performance']], feat: true, badge: warranty },
  { n: 'Growatt 5kVA Hybrid Inverter 48V — MOD 5000', c: 'solar-inverters', b: 'Growatt', p: 4950, cost: 3850, cmp: 5600, s: 11, w: 60, d: 'Runs fridge, TVs, fans and lights through the dark hours with pure sine wave and app monitoring. The core of a serious Ghana solar setup.', sp: [['Capacity', '5kVA/5kW'], ['Battery', '48V lithium/tubular'], ['Output', 'Pure sine, UPS-grade']], feat: true, badge: warranty },
  { n: 'Solar Home Kit 1.2kVA — Panel + Inverter + Batteries', c: 'solar-inverters', b: 'Luminous', p: 9850, cost: 7600, s: 8, w: 24, d: 'Turnkey: 4 × 250W panels, 1.2kW inverter, 2 × 150Ah gel, mounting and cables. Installed-ready for homes outside grid-reliable zones.', sp: [['Load', 'TVs, fans, lights, laptops'], ['Includes', 'Rails, MC4, 6m² cable']], tg: ['bundle'], badge: warranty },
  { n: 'Roof Mounting Kit — 4 Panels, Aluminium Rail', c: 'solar-inverters', b: 'Growatt', p: 1250, cost: 920, s: 20, w: 60, d: 'Anodised aluminium rails and clamps tested for Accra wind loads — non-penetrating options for sheet roofs.', sp: [['Material', '6005-T5 aluminium'], ['Capacity', '4 panels']], badge: genuine },
  { n: 'MPPT Solar Charge Controller 60A 12/24/48V', c: 'solar-inverters', b: 'Moko', p: 780, cost: 540, s: 30, w: 12, d: 'True MPPT with LCD telemetry — squeezes 25% more from your array than cheap PWM boxes.', sp: [['Tracking', '99% MPPT'], ['Display', 'LCD'], ['System', '12/24/48V auto']], badge: warranty },
  { n: 'Solar Pump Inverter 1.5kW with Panel Input', c: 'solar-inverters', b: 'Luminous', p: 3650, cost: 2750, s: 9, w: 24, d: 'Drill-site and irrigation pumping straight off the sun — soft-start protection for submersible pumps.', sp: [['Output', '1.5kW'], ['Input', 'PV direct'], ['Use', 'Borehole pumps']], tg: ['new'], new: true, badge: warranty },

  // ── Batteries & UPS/Stabilizers (6)
  { n: 'Tubular Battery 220Ah C10 — Tall Tubular', c: 'batteries-ups', b: 'Luminous', p: 2890, cost: 2250, cmp: 3300, s: 18, w: 36, d: 'The classic Ghanaian inverter battery. Tall tubular plates tolerate high water and heavy cycles far better than flat-plate car batteries.', sp: [['Capacity', '220Ah @ C10'], ['Type', 'Tall tubular flooded'], ['Life', '4–6 yrs maintained']], best: true, badge: warranty },
  { n: 'Gel Deep Cycle Battery 150Ah 12V', c: 'batteries-ups', b: 'Aptek', p: 1980, cost: 1520, s: 24, w: 24, d: 'Maintenance-free gel for inverters and solar — no topping up, safe in sealed rooms.', sp: [['Capacity', '150Ah'], ['Chemistry', 'Sealed gel'], ['Cycles', '1200 @ 50% DoD']], badge: warranty },
  { n: 'Lithium LiFePO4 100Ah 48V Rack Battery + BMS', c: 'batteries-ups', b: 'Growatt', p: 7850, cost: 5950, s: 8, w: 60, d: 'Five times the cycles of lead-acid, a tenth of the weight. Bluetooth BMS with low-temp charge protection for air-conditioned plant rooms.', sp: [['Energy', '5.12kWh'], ['Cycles', '6000 @ 80%'], ['Comms', 'RS485 + BT']], feat: true, tg: ['new'], new: true, badge: warranty },
  { n: 'UPS 650VA Line-Interactive — AVR Built-in', c: 'batteries-ups', b: 'Elepaq', p: 480, cost: 340, s: 70, w: 12, d: 'Keeps routers, decoders and CCTV alive through switching surges. AVR corrects brownouts without battery drain.', sp: [['VA', '650VA/360W'], ['Transfer', '<8ms'], ['Outlets', '4 surge-protected']], badge: genuine },
  { n: 'Voltage Stabilizer 5kVA Servo — Fridge & Freezer Guard', c: 'batteries-ups', b: 'FSP', p: 1380, cost: 1020, cmp: 1600, s: 22, w: 12, d: 'Servo-motor AVR that holds 220V steady for fridges and deep freezers — the cheapest insurance against compressor burnout.', sp: [['Capacity', '5kVA'], ['Regulation', '±5% servo'], ['Delay', '3-min compressor delay']], badge: warranty },
  { n: 'Elepaq 3kVA Mini Power Solution + 2 Batteries', c: 'batteries-ups', b: 'Elepaq', p: 3950, cost: 3050, s: 12, w: 24, d: 'Compact home backup: pure sine inverter with two 100Ah tubulars — lights, WiFi, TVs for hours off grid.', sp: [['Inverter', '3kVA pure sine'], ['Batteries', '2 × 100Ah tubular']], badge: warranty },

  // ── Generators (5)
  { n: 'Petrol Generator 2.5kVA — Recoil Start', c: 'generators', b: 'Hercules', p: 3250, cost: 2450, cmp: 3700, s: 16, w: 12, d: 'Dependable light-home backup for fans, TVs and fridge. Runs on petrol with AVR to protect electronics.', sp: [['Rating', '2.5kVA max'], ['Engine', '163F 212cc'], ['AVR', 'Yes']], best: true, badge: warranty },
  { n: 'Inverter Generator 3.2kVA Petrol — Super Quiet', c: 'generators', b: 'Yamaha', p: 9850, cost: 7600, s: 7, w: 24, d: 'Clean pure-sine power for laptops and medical devices; 58dBA at load — quiet enough that the neighbours never complain.', sp: [['Output', '3.2kVA peak'], ['Noise', '58dBA @ 75%'], ['THD', '<3%']], feat: true, badge: warranty },
  { n: 'Diesel Generator 5.5kVA Air-Cooled', c: 'generators', b: 'Hercules', p: 7200, cost: 5550, s: 10, w: 12, d: 'Workshop and retail backup that runs all day on diesel — air-cooled simplicity, no radiator to fuss with.', sp: [['Rating', '5.5kVA'], ['Fuel', 'Diesel'], ['Cooling', 'Air']], badge: warranty },
  { n: 'Soundproof Diesel 10kVA — Auto Start Ready', c: 'generators', b: 'Mikano', p: 24500, cost: 19200, s: 4, w: 24, d: 'Canopy-mounted quiet set for villas and clinics with AMF controller — takes load within 10 seconds of mains failure.', sp: [['Rating', '10kVA prime'], ['Canopy', 'Sound <75dBA @ 7m'], ['AMF', 'Ready']], badge: warranty },
  { n: 'Generator Parallel Cable & Changeover Box 60A', c: 'generators', b: 'Eastern Electric', p: 650, cost: 460, s: 28, w: 12, d: 'Safe isolation between ECG and generator power — double-throw changeover with interlock, no back-feed surprises.', sp: [['Rating', '60A DPDT'], ['Enclosure', 'IP54 metal']], badge: genuine },

  // ── Tools & Testers (6)
  { n: 'Fluke 117 Digital Multimeter — Electrician’s Standard', c: 'tools-testers', b: 'Fluke', p: 1680, cost: 1320, cmp: 1900, s: 20, w: 24, d: 'The multimeter pro electricians refuse to borrow. True-RMS, non-contact VoltAlert and a safety rating that means it.', sp: [['True RMS', 'Yes'], ['Safety', 'CAT III 600V'], ['Warranty', '3 years Fluke global']], feat: true, badge: warranty },
  { n: 'Clamp Meter 400A AC/DC with Inrush Mode', c: 'tools-testers', b: 'Fluke', p: 780, cost: 560, s: 34, w: 12, d: 'Measure AC compressor starts and inverter loads without cutting the cable. Essential for fault finding on site.', sp: [['Current', '400A AC/DC'], ['Inrush', '10-cycle capture'], ['Extras', 'Temp probe']], badge: warranty },
  { n: 'Insulation Resistance Tester 1000V Megger-style', c: 'tools-testers', b: 'Megger', p: 2950, cost: 2300, s: 9, w: 24, d: 'Certify wiring before energising — 250/500/1000V tests to find the damp cable before it trips the RCBO.', sp: [['Test V', '250/500/1000V'], ['Range', '2GΩ'], ['Use', 'PAT & installation testing']], badge: warranty },
  { n: 'Bosch GSB 550 Hammer Drill 550W', c: 'tools-testers', b: 'Bosch', p: 985, cost: 730, s: 30, w: 12, d: 'Rotary hammer duty for conduit runs and anchor fixings in block work — the Accra site staple.', sp: [['Power', '550W'], ['Mode', 'Drill/hammer'], ['Chuck', '13mm keyless']], best: true, badge: warranty },
  { n: 'Hydraulic Crimping Tool 16–50mm² + Dies', c: 'tools-testers', b: 'Eastern Electric', p: 620, cost: 430, s: 22, w: 12, d: 'Hex-crimp lugs and sleeves for service tails — a proper crimp that will not heat up in five years.', sp: [['Range', '16–50mm²'], ['Dies', 'Hex set included']], badge: genuine },
  { n: 'Socket Tester + RCD Function Checker', c: 'tools-testers', b: 'Carlit', p: 240, cost: 155, s: 48, w: 6, d: 'Plug in, read the LEDs: earth faults, reversed polarity, missing RCD. Fast trust-builder for inspections.', sp: [['Tests', '6 fault conditions'], ['RCD', '30mA trip check']], badge: genuine },

  // ── Fans & AC Accessories (5)
  { n: 'Rechargeable Ceiling Fan 56" with LED', c: 'fans-ac', b: 'Sunon', p: 745, cost: 530, cmp: 890, s: 40, w: 12, d: 'Keeps spinning 6+ hours after the light goes — DC motor, remote, and a downlight included. Ghana’s best-selling comfort upgrade.', sp: [['Sweep', '56 inch'], ['Backup', '≥6h rechargeable'], ['Motor', 'DC inverter']], best: true, badge: genuine },
  { n: 'Exhaust Fan 8" Wall-Mount — Kitchen & Bathroom', c: 'fans-ac', b: 'Sunon', p: 185, cost: 120, s: 90, w: 12, d: 'Moves steam and odour outside before it rusts your fittings. Shutter backdraft included.', sp: [['Size', '8 inch'], ['Airflow', '≈250 m³/h']], badge: genuine },
  { n: 'Standing Fan 18" Heavy Duty Metal', c: 'fans-ac', b: 'Tiger Soft', p: 420, cost: 295, s: 55, w: 12, d: 'All-metal 18-inch for workshops and chapo verandas — three speeds, wide oscillation, built to be bumped.', sp: [['Sweep', '18 inch'], ['Body', 'Metal']], badge: genuine },
  { n: 'AC Universal Remote + Receiver Kit', c: 'fans-ac', b: 'Carlit', p: 95, cost: 55, s: 130, w: 6, d: 'Lost the remote? This pairs to most split units and remembers settings through outages.', sp: [['Codes', '3000+ library'], ['Backup', 'Non-volatile']], badge: genuine },
  { n: 'Copper AC Pipe Coil 1/4"+3/8" × 15m Insulated', c: 'fans-ac', b: 'Eastern Electric', p: 680, cost: 500, s: 26, w: 12, d: 'Nitrogen-tested thin-wall copper with twin foam insulation — the professional installers’ line for split AC.', sp: [['Sizes', '1/4" + 3/8"'], ['Length', '15m coil'], ['Tested', 'Nitrogen']], badge: genuine },

  // ── Extensions & Surge (5)
  { n: 'Surge Protector Block 4-Socket 40,000A', c: 'extensions-surge', b: 'BVW', p: 168, cost: 105, s: 120, w: 12, d: 'Metal-oxide varistor protection for TV wall setups — protects against the switching spikes Ghana mains are known for.', sp: [['Outlets', '4 surge + 2 unprotected'], ['Joule', '40kA rated'], ['Cord', '3m 1.5mm²']], best: true, badge: genuine },
  { n: 'Extension Reel 25m 4-Socket 16A', c: 'extensions-surge', b: 'Eastern Electric', p: 285, cost: 205, s: 44, w: 12, d: 'Shock-resistant cable on a frame reel — event, workshop and compound runs without daisy-chaining adapters.', sp: [['Length', '25m'], ['Rating', '4 × 16A sockets']], badge: genuine },
  { n: 'Power Strip 6-Socket with USB-A/C ×4', c: 'extensions-surge', b: 'BVW', p: 220, cost: 145, cmp: 260, s: 85, w: 12, d: 'Desk-grade strip with 30W USB-C PD — charges laptops without bricks cluttering the counter.', sp: [['USB', '2×A + 2×C PD'], ['Switch', 'Per-socket']], badge: genuine },
  { n: 'Universal Travel Adapter ×2 — Surge Fused', c: 'extensions-surge', b: 'Carlit', p: 78, cost: 45, s: 160, w: 6, d: 'For guest houses and conferences: UK/EU/US pins with a real fuse, not the 5 pesewas kind.', sp: [['Standards', 'UK/EU/US'], ['Fuse', '10A replaceable']], badge: genuine },
  { n: 'Smart Plug 16A with Energy Monitoring', c: 'extensions-surge', b: 'Sonoff', p: 145, cost: 92, s: 95, w: 12, d: 'Meter the freezer, control the pump from your phone — works with Alexa and Google Home.', sp: [['Rating', '16A'], ['App', 'eWeChat'], ['Metering', 'Real-time kWh']], tg: ['new'], new: true, badge: genuine },

  // ── Security CCTV (6)
  { n: 'Hikvision 4-Camera 2MP DVR Kit', c: 'security-cctv', b: 'Hikvision', p: 3850, cost: 2950, cmp: 4400, s: 15, w: 24, d: 'Complete shop or villa kit: 4 turret cameras, 1TB DVR, cable and power — night vision that actually sees in the dark.', sp: [['Cameras', '4 × 2MP DS-2CE16'], ['Recorder', '1TB, 4ch'], ['Night', '20m IR']], feat: true, badge: warranty },
  { n: 'Ezviz C3WiFi Camera 3MP Pan-Tilt', c: 'security-cctv', b: 'Ezviz', p: 520, cost: 360, s: 60, w: 12, d: 'Auto-tracking PT camera with two-way talk — check on the kids or the guard from anywhere.', sp: [['Resolution', '3MP'], ['Motion', 'Human tracking'], ['Audio', '2-way']], best: true, badge: genuine },
  { n: 'Video Doorbell 1080p — WiFi, No Wires', c: 'security-cctv', b: 'Ezviz', p: 680, cost: 470, s: 38, w: 12, d: 'See and speak to whoever is at the gate from your phone. Rechargeable, weather sealed.', sp: [['Video', '1080p HDR'], ['Power', 'Rechargeable'], ['Night', 'IR']], tg: ['new'], new: true, badge: genuine },
  { n: 'Smart Lock Fingerprint + Code + App', c: 'security-cctv', b: 'Sonoff', p: 1480, cost: 1080, s: 18, w: 24, d: 'Bank-grade lock for apartment doors: 50 fingerprints, temporary codes for maids, app audit log.', sp: [['Unlock', 'Finger/code/card/app/key'], ['Logs', '100 events'], ['Battery', '6–9 months']], badge: warranty },
  { n: 'Wireless Alarm Kit — PIR + Door Sensors + Siren', c: 'security-cctv', b: 'Tiger Soft', p: 950, cost: 660, s: 26, w: 12, d: 'Deter before the break-in: 110dB siren, PIR movement and door contacts, remote arm/disarm.', sp: [['Siren', '110dB'], ['Sensors', '2 PIR + 4 reed'], ['Power', 'Mains + backup']], badge: genuine },
  { n: 'CCTV Cat6 Pass-Conduit Cable 305m — Siamese', c: 'security-cctv', b: 'Nexans', p: 890, cost: 650, s: 20, w: 12, d: 'One pull gives data + power for every camera — pure copper siamese for IP installs.', sp: [['Type', 'Cat6 + 2×0.5 power'], ['Length', '305m']], badge: genuine },

  // ── Smart Home (5)
  { n: 'Sonoff WiFi Wall Switch — Neutral + Live', c: 'smart-home', b: 'Sonoff', p: 185, cost: 118, s: 90, w: 12, d: 'Retrofit smart switching into Ghanaian back-boxes — works offline with local LAN control, no cloud dependency.', sp: [['Rating', '16A'], ['Control', 'eWeLink + Alexa/Google'], ['Modes', 'Timer, scene']], best: true, badge: genuine },
  { n: 'Smart Bulb Pack 4 × E27 RGBWW', c: 'smart-home', b: 'Sonoff', p: 320, cost: 210, s: 65, w: 12, d: 'Mood lighting for lounges and shops: 16M colours + warm-to-cool white, scenes on schedule.', sp: [['Colour', 'RGB + 2200-6500K'], ['Control', 'App & voice']], badge: genuine },
  { n: 'WiFi IR Blaster — Control AC & TV', c: 'smart-home', b: 'Sonoff', p: 210, cost: 135, s: 50, w: 12, d: 'Turn dumb AC and TV smart — switch on the cooling before you reach home in Spintex traffic.', sp: [['Coverage', 'IR line-of-sight'], ['Devices', 'Unlimited codes']], tg: ['new'], new: true, badge: genuine },
  { n: 'Smart Energy Monitor 3-Phase CT + App', c: 'smart-home', b: 'Sonoff', p: 480, cost: 320, s: 32, w: 12, d: 'See where the power goes per phase — invaluable on prepaid meters and inverter setups.', sp: [['Sensors', '3 × CT'], ['Accuracy', '±1%'], ['App', 'Real-time + history']], badge: genuine },
  { n: 'PIR Ceiling Occupancy Sensor 10A', c: 'smart-home', b: 'Sonoff', p: 125, cost: 78, s: 80, w: 12, d: 'Corridors and staff washrooms that light on arrival and fade on empty — trims ECG bills quietly.', sp: [['Range', '8m 360°'], ['Load', '10A']], badge: genuine },

  // ── Prepaid Meter Accessories (5)
  { n: 'Prepaid Meter Keypad — ECG Compatible', c: 'prepaid-meters', b: 'Aptek', p: 185, cost: 118, s: 110, w: 6, d: 'The missing keypad every prepaid household needs: durable membrane keys, clear token entry.', sp: [['Standard', 'STS compliant'], ['Battery', 'AAA ×2']], best: true, badge: genuine },
  { n: 'Lockable Meter Box 3-Phase — IP54', c: 'prepaid-meters', b: 'BVW', p: 230, cost: 150, s: 55, w: 12, d: 'Polycarbonate enclosure that protects the meter from sun and meddling hands — padlock hasps included.', sp: [['IP', 'IP54'], ['Size', '3-phase footprint']], badge: genuine },
  { n: 'STS Token Card Reader — Bulk Vend', c: 'prepaid-meters', b: 'Aptek', p: 265, cost: 175, s: 42, w: 12, d: 'For landlords and estates vending tokens for multiple units — keyboard-wedge speed, no typos.', sp: [['Type', 'STS keyboard wedge'], ['Use', 'Bulk token entry']], badge: genuine },
  { n: 'Meter CT Sensor — Anti-Tamper Current Check', c: 'prepaid-meters', b: 'Moko', p: 540, cost: 380, s: 24, w: 12, d: 'Detects bypass tricks in seconds — the peace-of-mind accessory estates and landlords install.', sp: [['Output', 'Pulse metering'], ['Fit', 'Split-core']], badge: genuine },
  { n: 'Weatherproof Outdoor Meter Cabinet with Isolator', c: 'prepaid-meters', b: 'BVW', p: 680, cost: 480, cmp: 780, s: 18, w: 12, d: 'Complete compound-entry setup: sealed cabinet, 60A isolator, earth bar — ECG-standard look.', sp: [['IP', 'IP54'], ['Included', 'Isolator + busbars']], badge: warranty },
];
